# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = python_intermediate_tutorial
SUB_SRC_FILES = \
    preface.xml \
    python_intermediate_tutorial.xml \
    ch01_python_2x_3x.xml \
    ch02_python_module_package.xml \
    ch03_python_gui_lib.xml \
    ch04_python_str_encoding.xml \
    ch05_python_cmd_para.xml \
    ch06_python_csv_excel.xml \
    ch07_python_html_parse.xml \
    ch08_python_website_scrape.xml \
    ch09_python_regular_expression.xml \
    ch10_python_web_framework.xml \
    ch11_python_cookie_http.xml \
    ch12_python_database.xml \
    ch13_python_others.xml \
    reference.xml \

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk